site_name: RPL Task Documentation
theme:
  logo: assets/logo3.png
  favicon: assets/favicon.ico
  name: material
  language: en
  features: 
    - content.code.annotation
    - content.code.copy
  palette: 
    scheme: slate
    primary: red
    accent: red
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
