site_name: RPL Task Documentation
theme:
  name: material
  language: en
  features: 
    - content.code.annotation
    - content.code.copy
  palette: 
    scheme: slate
    primary: red
    accent: red

